### ISSUE TITLE
TODO: Abstraction issues to fix

### ISSUE THREAD

**Issue by Trinsdar** [GregTech-Intergalactical/AntimatterAPI#189]
#### forge:
- [x] arrp seems to be having issues with client stuff being added, I probably am missing something on forge. the blockstates and stuff work once you reload textures, so it's just a matter of when the resource pack is added
everything else seems to be working
#### fabric:
- [x] WorldRenderEventw.BLOCK_OUTLINE is commented cause I don't know how to supply the BlockHitResult target and float partialTicks
```
WorldRenderEvents.BLOCK_OUTLINE.register(((worldRenderContext, blockOutlineContext) -> ClientEvents.onBlockHighlight(worldRenderContext.worldRenderer(), worldRenderContext.camera(), ?, ?, worldRenderContext.matrixStack(), worldRenderContext.consumers())));
```
- [ ] don't know what event to register to for `ClientEvents.onRenderDebugInfo`, tried `WorldRenderEvents.BEFORE_DEBUG_INFO`, but that doesn't provide the `List<String>` required
https://github.com/GregTech-Intergalactical/AntimatterAPI/blob/726c8ced2c381cfbe52f73cfab95289e4a5100c6/common/src/main/java/muramasa/antimatter/client/event/ClientEvents.java#L137-L157
- [x] fabricated-forge-modeldata doesn't seem to be working, which means none of the machine, cable, and pipes render properly in world right now
very difficult to test the machines cause of that

Update: found new issues
- [x] Guis seem to be broken, like they render correctly, but widgets don't update correctly at all
- [x] Item caps seem to have sync issues or something on fabric, gotta figure out what's up there
