### ISSUE TITLE
TODO: fluid issues to fix

### ISSUE THREAD

**Issue by Trinsdar** [GregTech-Intergalactical/AntimatterAPI#219]
- [x] cells don't work properly when right clicking tiles
- [x] buckets don't work properly in cell slots
- [x] higher storage cells don't work properly at all
- [x] picking up fluids seems to crash on fabric
- [ ] fluid colors are broken on fabric
